version: "3.8"
services:
  database:
    image: postgres
    container_name: db_rentalX
    hostname: db_rentalX
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db_rentalx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentalx-app
  app:
    build: .
    container_name: rentalX
    hostname: rentalX
    # restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - rentalx-app
volumes:
  pgdata:
    driver: local
networks:
  rentalx-app:
    driver: bridge